version: "3"

services:
  registry-service:
    image: node-service
    command: node index REGISTRY 3000
    build: ./
    environment:
      NODE_ENV: production
    ports: 
      - 3010:3000
  auth-service:
    image: node-service
    build: ./
    depends_on: 
      - registry-service
    command: node index AUTH 3000
    
